name: Build and Deploy 

on:  
  push: 
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pokemon-api:latest ./rick-and-morty/app

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-api:latest

    - name: Install kubectl
      run: |
        KUBECTL_VERSION="v1.26.0"
        echo "Kubernetes version: $KUBECTL_VERSION"
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2

    - name: Set up kubeconfig for EKS
      run: aws eks update-kubeconfig --region us-east-2 --name cluster

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./rick-and-morty/k8s/deployment.yaml
        kubectl apply -f ./rick-and-morty/k8s/service.yaml
        kubectl apply -f ./rick-and-morty/k8s/ingress.yaml

    - name: Verify deployment
      run: kubectl get pods
